// ─────────────────────────────────────────────────────────────────────────────
//  MyAvatar.tsx — generated by Avatar Builder
//
//  Drop this single file into any React + TypeScript project.
//  Zero runtime dependencies — all SVG paths are baked in.
//
//  Avatar configuration snapshot
//    face      : BeardFace1
//    eyes      : Normal
//    mouth     : NormalThin
//    hair      : Style12
//    accessory : Earphone
//    outfit    : Outfit04
//    backColor : #348E2C
// ─────────────────────────────────────────────────────────────────────────────

import React, { useRef, useEffect } from "react";

// ─── Props ───────────────────────────────────────────────────────────────────
//
//  size          number   default 400    width & height in px
//  breathe       boolean  default true   Apple-like breathing loop
//  mouseFollow   boolean  default true   rAF-spring cursor parallax
//
//  Usage:
//    import { MyAvatar } from './MyAvatar';
//    <MyAvatar />
//    <MyAvatar size={300} />
//    <MyAvatar size={400} breathe={false} mouseFollow={false} />

// ─── Styles ──────────────────────────────────────────────────────────────────
//
//  All rules are scoped to .ab-* class names — they will not conflict with
//  styles already present in your project.
//
//  You can safely move these rules into your global stylesheet if you prefer
//  not to inject them at runtime via dangerouslySetInnerHTML.

const AVATAR_CSS = `
/* ─── Breathing animation ─────────────────────────────────────────────────────
 *
 * Values mirror the Avatar Builder's Motion animation exactly:
 *   translateY  0 → -4px → 0     (gentle upward float)
 *   rotateZ     0 →  1deg → 0    (subtle head tilt)
 *   scale       1 →  1.01 → 0    (slight swell)
 *   duration    4s  ·  easing: ease-in-out  ·  origin: bottom center
 * ─────────────────────────────────────────────────────────────────────────── */
@keyframes ab-breathe {
  0%, 100% { transform: translateY(0px)  rotateZ(0deg) scale(1);    }
  50%       { transform: translateY(-4px) rotateZ(1deg) scale(1.01); }
}

.ab-breathe {
  animation:        ab-breathe 4s ease-in-out infinite;
  transform-origin: bottom center;
  display:          inline-flex;
}

/* ─── Mouse-follow parallax ────────────────────────────────────────────────────
 *
 * The useMouseFollow hook writes --mx / --my (range −1 … 1) on the container.
 * Each layer multiplies those vars by its own depth offset so that moving the
 * cursor makes the avatar look around with a convincing sense of 3-D depth.
 *
 * To tune a layer: change its px multipliers below.
 * To disable all:  remove the 'ab-follow' class from the wrapper div.
 * ─────────────────────────────────────────────────────────────────────────── */
.ab-follow svg { overflow: visible; }

/* front → back depth order */
.ab-follow g[data-part='eyes']  { transform: translate(calc(var(--mx, 0) * 12px), calc(var(--my, 0) *  8px)); }
.ab-follow g[data-part='nose']  { transform: translate(calc(var(--mx, 0) * 12px), calc(var(--my, 0) *  8px)); }
.ab-follow g[data-part='mouth'] { transform: translate(calc(var(--mx, 0) * 10px), calc(var(--my, 0) *  7px)); }

/* face tilts on the X axis — transform-box + origin keep pivot centred */
.ab-follow g[data-part='face'] {
  transform:        translate(calc(var(--mx, 0) * 5px), calc(var(--my, 0) * 4px))
                    rotate(calc(var(--mx, 0) * 1.5deg));
  transform-box:    fill-box;
  transform-origin: 50% 50%;
}

.ab-follow g[data-part='hair']      { transform: translate(calc(var(--mx, 0) *  5px), calc(var(--my, 0) * 4px)); }
.ab-follow g[data-part='accessory'] { transform: translate(calc(var(--mx, 0) * 10px), calc(var(--my, 0) * 7px)); }
.ab-follow g[data-part='outfit']    { transform: translate(calc(var(--mx, 0) *  2px), calc(var(--my, 0) * 1px)); }
`;

// ─── useMouseFollow ───────────────────────────────────────────────────────────
//
//  Smooth rAF-based spring interpolation for cursor tracking.
//
//  Each animation frame:
//    1. Lerps (cx, cy) toward the raw cursor position (tx, ty).
//    2. Writes --mx / --my onto the container element as CSS custom properties.
//    3. The .ab-follow rules above multiply those vars per layer — no JS
//       needed at render time, making this completely jank-free.
//
//  LERP = 0.09 → relatively smooth.  Increase toward 1.0 for snappier tracking.

function useMouseFollow(
  ref: React.RefObject<HTMLDivElement | null>,
  enabled: boolean,
) {
  useEffect(() => {
    const el = ref.current;
    if (!el || !enabled) return;

    let frameId: number;
    let cx = 0,
      cy = 0; // current smoothed value
    let tx = 0,
      ty = 0; // raw target from cursor
    const LERP = 0.09;

    const tick = () => {
      cx += (tx - cx) * LERP;
      cy += (ty - cy) * LERP;
      el.style.setProperty("--mx", cx.toFixed(4));
      el.style.setProperty("--my", cy.toFixed(4));
      frameId = requestAnimationFrame(tick);
    };

    const onMove = (e: MouseEvent) => {
      const { width, height, left, top } = el.getBoundingClientRect();
      tx = ((e.clientX - left) / width - 0.5) * 2;
      ty = ((e.clientY - top) / height - 0.5) * 2;
    };

    const onLeave = () => {
      tx = 0;
      ty = 0;
    };

    frameId = requestAnimationFrame(tick);
    el.addEventListener("mousemove", onMove);
    el.addEventListener("mouseleave", onLeave);

    return () => {
      cancelAnimationFrame(frameId);
      el.removeEventListener("mousemove", onMove);
      el.removeEventListener("mouseleave", onLeave);
    };
  }, [ref, enabled]);
}

// ─── AvatarSVG ───────────────────────────────────────────────────────────────
//
//  All paths are inlined — no external assets or imports required.
//  This block is machine-generated; treat it as a compiled artefact.

function AvatarSVG({ size }: { size: number }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 414 414"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      role="img"
      aria-label="Avatar Preview"
    >
      <circle cx="207" cy="207" r="154" fill="#8FED82" />
      <clipPath id="avatar-clip-r6">
        <circle cx="207" cy="207" r="154" />
      </clipPath>
      <g clipPath="url(#avatar-clip-r6)">
        <g transform="translate(102.87255859375, 126.2861328125)">
          <g opacity="1">
            <g data-part="face">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="193"
                height="243"
                fill="none"
              >
                <path
                  fill="#FEE4BF"
                  d="M192.4 217.896c-.7.5-1.5 1-2.2 1.5-.8.5-1.5 1-2.3 1.4-.7.4-1.3.8-2 1.2-.1.1-.2.1-.3.2-2.3 1.4-4.7 2.7-7.1 3.9-.7.4-1.5.8-2.2 1.1 0 0-.1.1-.2.1l-2.4 1.2c-1.6.8-3.3 1.5-4.9 2.2-.8.4-1.7.7-2.5 1s-1.7.7-2.5 1-1.7.7-2.5 1h-.1c-.8.3-1.7.6-2.5.9-1.8.6-3.7 1.2-5.5 1.8-.6.2-1.3.4-1.9.6q-2.85.9-5.7 1.5c-.7.2-1.4.3-2.2.5-1.8.4-3.7.8-5.5 1.2-.4.1-.7.1-1.1.2-.6.1-1.3.2-1.9.3-.9.1-1.7.3-2.6.4-.4.1-.8.1-1.2.2-.5.1-1.1.2-1.7.2-1.6.2-3.3.4-4.9.6-.5.1-1.1.1-1.6.2h-.1c-.7.1-1.4.1-2.1.2s-1.4.1-2.1.1c-.4 0-.9.1-1.3.1-.8 0-1.5.1-2.2.1-1 0-1.9.1-2.9.1h-5c-42.1-.6-80.1-18.5-107.1-46.9 0 0 0-.1-.1-.1 3.1-6.1 14.6-17.1 26.6-26.2 15.2-11.5 36.7-18.6 36.7-18.6s14.1-2.3 66.4 8.6c39.9 8.4 56.9 42.5 62.7 58.2"
                />
                <path
                  fill="#FEE4BF"
                  d="M140.801 187.396c-2.1 10.3-15.7 16.4-38.6 7.2-28.1-11.4-38.9-43.499-38.9-43.499-1.5-23-5-42.701-5-42.701 32.5-2.8 70.9 35.201 70.9 35.201l4.4 18.799c.4 1.6 1.2 3 2.4 4 2.1 3.6 6.2 14.4 4.8 21"
                />
                <path
                  fill="#EFBD9C"
                  d="M135.999 166.497c-19.1-1-33.2-3.8-48.3-30.9 12.8 11.3 27.9 15.6 43.8 17.6l2.1 9.2c.4 1.7 1.2 3.1 2.4 4.1"
                />
                <path
                  fill="#FEE4BF"
                  d="M175.501 45.997c1.8 8.4 2.7 15.2-2.2 37.6s4.5 44.8-19.1 65.3c-15.9 13.8-43.7 16.4-65.9 1.3-7.5-5.1-14.4-12.2-20-21.5-4.4-7.3-9.5-14.2-15.2-20.5-7.9-8.6-17.4-25.9-12.7-56.5 7.6-49.8 56.9-55.5 86-50s44.2 22.1 49.1 44.3"
                />
                <path
                  fill="#FEE4BF"
                  d="M79.8 85.096s-3.1-15-17.7-13.2c-12.6 1.6-17 31.8 11.6 40.2"
                />
                <path
                  stroke="#423232"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeMiterlimit="10"
                  strokeWidth="3"
                  d="M72.8 98.397s-3.6-2.3-3.2-6.3c.6-4.7 0-7.6-2.2-8.5-5.5-2.3-6.6 4.1-6.4 4.9"
                />
                <g data-part="nose">
                  <path
                    fill="#EFBD9C"
                    d="M149.101 108.096s3.8.2 7.4-4.1c2-2.4 3.7-5.4 2.6-6.3-1.1-1-19.2 1.8-20.4 4.2s5.8 6.2 10.4 6.2"
                  />
                  <path
                    stroke="#423232"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeMiterlimit="10"
                    strokeWidth="3"
                    d="M152.1 74.496s.2 9.5 6.3 20.1c2.7 4.7-1.4 12.4-10.3 13.7"
                  />
                </g>
                <path
                  fill="#423232"
                  d="M167.8 129.997q0 .15 0 0-.15.15 0 0c-2.5 6.5-6.6 12.7-13.6 18.8-15.9 13.8-43.7 16.4-65.9 1.3q-3.75-2.55-7.2-5.7-2.4-3-4.2-6.3c-7.2-13.5-4.1-26.1-4.1-26.1s4.1.1 9 9.7c4.1 8 19.9 7.7 26.4-7.3 7.2-16.7 25.2-9.4 29.3-7.8s10.5 1.6 10.5 1.6c16.2-.2 11.3 10.7 13 16.7 2.5 8.2 6.8 5.1 6.8 5.1"
                />
              </svg>
            </g>
          </g>
        </g>
        <g transform="translate(203.1171875, 174.09765625)">
          <g opacity="1">
            <g data-part="eyes">
              <g>
                <svg
                  viewBox="0 0 78 43"
                  width="78"
                  height="43"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    fill="#423232"
                    d="M13.433 37.048c-2.4-.1-4.2-2.1-4-4.5l.1-2.8c.1-2.4 2.1-4.2 4.5-4 2.4.1 4.2 2.1 4 4.5l-.1 2.8c-.1 2.3-2.1 4.1-4.5 4M55.533 38.548c-2.2-.1-3.9-2-3.8-4.2l.1-2.6c.1-2.2 2-3.9 4.2-3.8s3.9 2 3.8 4.2l-.1 2.6c-.1 2.2-2 3.9-4.2 3.8"
                  />
                  <path
                    stroke="#423232"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeMiterlimit="10"
                    strokeWidth="3"
                    d="M23.133 31.248s-2.6-3.7-7.1-4.4c-3.7-.6-7.8 1.2-8.4 3.3M52.633 32.147s0-3.2 4.6-3.2c3.8 0 5.4 3.5 5.4 3.5"
                  />
                  <path
                    fill="#423232"
                    d="M27.233 15.147c2.1.7 4.2-1.2 3.8-3.5-.2-1.2-.7-2.4-1.7-3.3-3-2.7-15.4-5.1-22.9-1.6-6.6 3.2 11.2 5.2 20.8 8.4M57.133 16.747c-1.7.6-3.5-1.2-3.2-3.3.1-1.1.5-2.2 1.3-3 2.4-2.4 10.6-4.3 15.8-.6 4.5 3.1-6.1 4-13.9 6.9"
                  />
                </svg>
              </g>
            </g>
          </g>
        </g>
        <g transform="translate(220.32513427734375, 239.43896484375)">
          <g opacity="1">
            <g data-part="mouth">
              <svg
                viewBox="0 0 30 16"
                width="30"
                height="16"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  stroke="#FEE4BF"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeMiterlimit="10"
                  strokeWidth="2.468"
                  d="M23.5 8.5C19.1 11.1 12.1 9.5 7 6"
                />
              </svg>
            </g>
          </g>
        </g>
        <g transform="translate(85.10601806640625, 104.50048828125)">
          <g opacity="1">
            <g data-part="hair">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 250 207"
                width="250"
                height="207"
                fill="none"
              >
                <path
                  fill="#99807F"
                  d="M53.506 78.929c-4 29.2 9.1 49.3 16.1 57.7 8 9.6 8.7 16.9 8.7 16.9 4.1-2.3 9.3-12.6 9.4-18-25-9.6-20.5-37.5-8.3-39.1 12.8-1.6 16.8 9.8 17.5 12.6 3.2-3.8 3-25.4 6.7-38.9-16.1 5.8-33.1 8.9-50.1 8.8"
                />
                <path
                  fill="#423232"
                  d="M180.906 41.33c-6.2-3-11.5-9.3-19.3-12.4-45.6-18.5-94.5.4-105.2 36.9-1.4 4.6-2.3 9-2.9 13.2 17 .1 34.1-3.1 50.1-8.8 1.6-5.8 3.9-10.2 7.6-11 19.3-4.2 37.4-6.3 60.3-3.2 8.5 1.2 15-2.7 19.4 8.1.7 2.1 1.3 4.2 1.8 6.4 1.6 7.1 2.4 13.1-.3 28.3 1.8-2.9 4.1-9.1 5.1-14.4 3.2-18.7 1.7-34.3-16.6-43.1"
                />
                <path
                  fill="#423232"
                  d="M193.604 74.73c1 4.8 7.1 4.4 8-.4 1.3-7 1.9-15.4.8-24.9-5.2-44.4-49.3-59.4-40.8-29.8 0 0-11.6-18.6-37.7-19.6-22.4-.8-8.8 15.1-8.8 15.1s-27.4-10-56.9 5c-25.7 13.1-1.9 24.6-1.9 24.6s-19.5 10.3-19.8 32.5c-.2 16.6 53.5 17.3 73.9 5.2 10.6-6.3 15.6-17.2 26.4-23.6 18.9-11.3 23.8 14.2 33.9 4.8 11.8-10.8 20.3-2.2 22.9 11.1"
                />
              </svg>
            </g>
          </g>
        </g>
        <g transform="translate(70.3125, 250.3779296875)">
          <g opacity="1">
            <g data-part="outfit">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="290"
                height="190"
                fill="none"
              >
                <path
                  fill="#BEE3EB"
                  d="M254.046 149.29H1.246s1.5-46.4 16.7-79.5c11.5-25 38.6-38.9 58.8-46.1 5.7-2 10.9-3.5 14.9-4.6 0 .5.1.9.1 1.4 0 0 10.8 32.1 38.9 43.5 22.9 9.3 36.5 3.1 38.6-7.2 1.3-6.6-2.8-17.4-4.9-20.9-1.2-1-2-2.5-2.4-4l-.8-3.3c1.9-.4 3.7-.9 5.5-1.5.6-.2 1.1-.4 1.7-.6 12.9 3.4 32.3 11.5 55.2 30.7 25.9 21.6 30.5 92.1 30.5 92.1"
                />
                <path
                  fill="#fff"
                  d="M121.944 74.39c-34.5-15.5-47.9-43.2-45.3-50.7 0 0 0-.1.1-.2 1.8-3.7 4.7-6.7 8.3-8.8 2-1.2 4.2-2.3 6-2.9.1 1.4.5 5.8.6 7.3 0 .5.1.9.1 1.4 0 0 6.4 23.9 34.5 35.3 22.9 9.3 37.1 3.2 38.6-7.2 1.7-11.5-4.8-19.8-4.8-19.8 1.9-.4 4.9-1.1 6.7-1.7 4.4 5.3 8.9 10.6 10.6 24.6 2.4 20.1-19.7 38.8-55.4 22.7"
                />
                <path
                  stroke="#544D4D"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeMiterlimit="10"
                  strokeWidth="3"
                  d="m50.746 149.289-4.5-37.1M225.345 99.59s-3 7.3-2.1 14.6 3.5 18-.2 35.1"
                />
              </svg>
            </g>
          </g>
        </g>
        <g transform="translate(150, 209)">
          <g opacity="1">
            <g data-part="accessory">
              <svg
                viewBox="0 0 140 198"
                width="140"
                height="198"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  fill="#fff"
                  d="M20.713 4.899s-8-1.2-7.4 10c.3 5.7.3 8.8.2 10.4-.1 1.1.6 2.1 1.6 2.5 1.2.5 2.5 0 3.1-1.2.9-1.6 1.9-3.8 1.9-5.6 0-3 3.2-5.7 3.2-5.7s-2.9-2.5-2.6-10.4"
                />
                <path
                  fill="#fff"
                  d="M44.913 197.698c-.8-.9-32.2-54.6-27.5-74.8 3.2-13.9-1-29.9-4.7-44-1.5-5.8-2.9-11.2-3.7-16-1.4-8.3-.4-16.2 3-23.5 3.7-8.2 3.1-15.3 3.1-15.4l2-.2c0 .3.6 7.8-3.3 16.4-3.2 6.9-4.1 14.5-2.8 22.4.8 4.7 2.2 10.1 3.7 15.9 3.8 14.3 8 30.6 4.7 45-4.4 19.2 26.9 72.9 27.1 73.1z"
                />
                <path
                  fill="#E5E5E5"
                  d="M13.613 20.699c.1 2.2 0 3.7 0 4.6-.1 1.1.6 2.1 1.6 2.5 1.2.5 2.5 0 3.1-1.2.9-1.6 1.9-3.8 1.9-5.6v-.4c-2.1.8-4.5 1.4-6.6.1"
                />
                <path
                  fill="#fff"
                  d="M107.713 87.198c-.7 4.6-.8 11.9-1 20.4-.3 16.4-10 80.3-14.7 90.4l-1.8-.8c4.5-9.8 14.2-73.4 14.5-89.6.2-8.5.3-15.9 1-20.7 1.5-10.1.4-17.7-.2-20.9.3-.3.6-.5.9-.8.3-.2.5-.5.8-.7.6 2.6 2.3 10.9.5 22.7"
                />
              </svg>
            </g>
          </g>
        </g>
      </g>
    </svg>
  );
}

// ─── MyAvatar ─────────────────────────────────────────────────────────────────

const MyAvatar = ({
  size = 400,
  breathe = true,
  mouseFollow = true,
}: {
  size?: number;
  breathe?: boolean;
  mouseFollow?: boolean;
}) => {
  const ref = useRef<HTMLDivElement>(null);
  useMouseFollow(ref, mouseFollow);

  const classes = [mouseFollow ? "ab-follow" : "", breathe ? "ab-breathe" : ""]
    .filter(Boolean)
    .join(" ");

  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: AVATAR_CSS }} />
      <div
        ref={ref}
        className={classes}
        style={{ width: size, height: size, display: "inline-block" }}
      >
        <AvatarSVG size={size} />
      </div>
    </>
  );
};


export default MyAvatar;